# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: CmdLine@2
        inputs:
          script: |
            cd blacklist
            docker build -t registry.aspcode.net/javablacklist .
            docker login -u $(REGISTRY_USERNAME) -p $(REGISTRY_PASSWORD)  https://registry.aspcode.net
            docker push registry.aspcode.net/javablacklist