### check one
GET http://localhost:8080/api/stefan/blacklistcheck/eh@test.com

### get all
GET http://localhost:8080/api/stefan/blacklist


### add one
POST  http://localhost:8080/api/stefan/blacklist
Content-Type: application/jsonw

{
    "email":"stefan6@aaa.com",
    "name":"Stefan Holmberg",
    "isOk":true
}


### UPDATE one
PUT  http://localhost:8080/api/stefan/blacklist/stefan6@aaa.com
Content-Type: application/json

{
    "name":"Stefan Holmberg",
    "isOk":"true"
}
