server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ApiServer
        hikari:
            username: root
            password: hejsan123
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect 
                format_sql: true
                globally_quoted_identifiers: true
        show-sql: true
